version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    commit-message:
      prefix: '[skip netlify]'
      include: scope
