name: Scheduled Build
on:
  schedule:
    - cron: '0 15 * * *'  # UTC -> 8:00 MDT/9:00 MST
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_SCHEDULED_BUILDS_KEY }}
